### ISSUE TITLE
[DSpace 7 Upgrade] Port custom emails to new email templates

### ISSUE THREAD

**Issue by tamu-sad-iii** [TAMULib/DSpace#200]
Merging blocked by [SPIKE]()

Find out if we have any custom email templates to port over.

From: https://github.com/TAMULib/DSpace/tree/tamu-dspace-6.3/dspace/config/emails
To: https://github.com/TAMULib/DSpace/tree/dspace-7_x-sprint2/dspace/config/emails

**Comment by Dbreck-TAMU** [comment]
Ported over: 
bte_batch_import_error
bte_batch_import_success
subscriptions

Awaiting response regarding legacy email templates.

**Comment by Dbreck-TAMU** [comment]
@jcreel - Do we want to reimplement the custom emails from this template as well? It seems the last few commits we've gone back to using the standard DSpace email templates.  

https://github.com/TAMULib/DSpace/commit/0b774bb0eb08e162fed7956f3c73a229d286abdd

There may be some templates in DSpace production that are not present in GitHub.

**Comment by wwtamu** [comment]
- [ ] Verify customized email templates are being utilized by TAMU customized DSpace 7
- [ ] Compare current DSpace 7 email templates against current production DSpace 6 (OAKTrust)
- [ ] Verify email templates currently used in production DSpace 6 match/resemble the templates used in DSpace 7
  There may be some that were added that bypassed version control.

**Comment by wwtamu** [comment]
Have DSpace 7 in dev send a few emails and confirm they have appropriate templated values.

**Comment by wwelling** [comment]
Test email sent via subscription.
