### ISSUE TITLE
[DSpace 7 Upgrade] Migrate existing discovery configuration

### ISSUE THREAD

**Issue by tamu-sad-iii** [TAMULib/DSpace#205]
Our existing default configuration can be found here:
https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/config/spring/api/discovery.xml#L96 
Line 96 to 229

~Confirm with James, if this bean `homepageConfiguration` too would be required.~
There are other beans present in this configuration file - that would require migration.

**Comment by Dbreck-TAMU** [comment]
Will not be doing the homepage configuration - per James request. 

Still want to have the TAMU customization of line 96-229 implemented.
Line 160-307 (without additions) in DSpace 7

**Comment by jcreel** [comment]
Upon further investigation of discovery functionality in DSpace 7, it appears that not all the searchFilter beans will be required.
Furthermore, the advanced search of DSpace 6 and prior has been replaced with Solr syntax in all the searchboxes.

Given these considerations, we will need to consult our UX librarians for recommendations on next steps with customizing the search capabilities in DSpace 7.

**Comment by tamu-sad-iii** [comment]
Compare and bring over discovery customizations from 6x.
