### ISSUE TITLE
[DSpace 7 Upgrade] Reimplement RDF map collections and communities metadata

### ISSUE THREAD

**Issue by tamu-sad-iii** [TAMULib/DSpace#211]
Blocks [#68](https://github.com/TAMULib/tl_docker/issues/68)

Original PR: https://github.com/TAMULib/DSpace/pull/155

**Comment by jsavell** [comment]
At some point, the DSpace RDF app will have to be configured and a triple store (fuseki) set up for 7.

https://github.com/TAMULib/DSpace/pull/103/files

https://wiki.lyrasis.org/display/DSDOC7x/Linked+%28Open%29+Data
