### ISSUE TITLE
[DSpace 7 Upgrade] Test Indexing Writing Bitstreams and Community Collection Names

### ISSUE THREAD

**Issue by tamu-sad-iii** [TAMULib/DSpace#217]
Verify functionality of a customization done for https://github.com/TAMULib/DSpace/issues/203.

Should be done in with https://github.com/TAMULib/tl_docker/issues/69.

**Comment by wwtamu** [comment]
Should be verified with https://github.com/TAMULib/tl_docker/issues/69
