### ISSUE TITLE
[DSpace 7 Upgrade] Reimplement describe step for submission workflow customizations

### ISSUE THREAD

**Issue by tamu-sad-iii** [TAMULib/DSpace#219]
~Blocks https://github.com/TAMULib/DSpace/issues/202~

org.dspace.app.xmlui.aspect.submission.submit.DescribeStep

May need to be transferred to DSpace repository or another issue be created in DSpace repository.

**Comment by Dbreck-TAMU** [comment]
is in XMLUI package (was removed in dspace 7).  -- Want to maintain feature parity. 

Could create a custom UI override. 

Add documentation regarding to this process. Could help with issue [#49](https://github.com/TAMULib/dspace-angular/issues/49). 

Could have William/James walk through the process and 49 to follow as it follows the same process but for a different customization.

**Comment by tamu-sad-iii** [comment]
Here is the DescribeStep in 7:

https://github.com/TAMULib/DSpace/blob/tamu-dspace-7_x/dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/DescribeStep.java

Here is the DescribeStep in 6:

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace-api/src/main/java/org/dspace/submit/step/DescribeStep.java

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java

Here is the TAMU Customized DescribeStep in 6:

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/additions/src/main/java/org/dspace/submit/step/DescribeStep.java

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java

**Comment by tamu-sad-iii** [comment]
The `detailed_name` custom field of the [DescribeStep](https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java#L237) customization has been [disabled](https://github.com/TAMULib/DSpace/commit/25caa4b5c8fabf9e450643614fd0b529f90c2e28) from the [input-forms.xml](https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/config/input-forms.xml#L221).

I have confirmed that this customization is no longer in use on OAKTrust or dspacepre1 for the applicable [form-map collections](https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/config/input-forms.xml#L16).

If enabled we would see `Enter the names of the authors of this item. For TAMU Faculty, Staff, and Students please use TAMU email address (@tamu.edu)` as the Authors input field.

`<name-map collection-handle="1969.1/93296" form-name="facultyPub"/>`

![Image](https://github.com/TAMULib/DSpace/assets/144841721/e7ce8002-7336-45c0-869e-cb76c4aeb8dc)

![Image](https://github.com/TAMULib/DSpace/assets/144841721/967f3da0-dcfd-4dd5-b479-64aaca228494)


`<name-map collection-handle="1969.1/187506" form-name="facultyPub"/>`

![Image](https://github.com/TAMULib/DSpace/assets/144841721/b46a5a49-6bf4-4261-a26c-72fce711b5b4)

![Image](https://github.com/TAMULib/DSpace/assets/144841721/ec25bfd1-cfe7-4c1c-94f4-6abb41105114)

**Comment by tamu-sad-iii** [comment]
@jcreel do we require bringing over the [Java processing code](https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java#L546) behind the `detailed_name` custom field for DSpace 7 having available for submission input form?

**Comment by tamu-sad-iii** [comment]
Upon further investigation, without the need for the `detailed_name` step there is no Java code customizations necessary.

https://raw.githubusercontent.com/TAMULib/DSpace/tamu-dspace-6.3/dspace-api/src/main/java/org/dspace/submit/step/DescribeStep.java

compared with

https://raw.githubusercontent.com/TAMULib/DSpace/tamu-dspace-6.3/dspace/modules/additions/src/main/java/org/dspace/submit/step/DescribeStep.java

and 

https://raw.githubusercontent.com/TAMULib/DSpace/tamu-dspace-6.3/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java

compared with 

https://raw.githubusercontent.com/TAMULib/DSpace/tamu-dspace-6.3/dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java

has no additional Java code customizations.

**Comment by tamu-sad-iii** [comment]
Customizations for this step will be included with #202.
